FactoryGirl.define do
  factory :work_order_detail, :class => 'WorkOrderDetails' do
    smsid "MyString"
buid "MyString"
sms "MyString"
contact_phone_number "MyString"
business_unit "MyString"
versionid "MyString"
tzi "MyString"
fsruserid "MyString"
fsrbuid "MyString"
previous_fsr_buid "MyString"
dispatcher_id "MyString"
key1 "MyString"
problem_code "MyString"
key2 "MyString"
order_date_time "2015-06-24 18:58:00"
due_date_time "2015-06-24 18:58:00"
jobtype "MyString"
jobclass "MyString"
tech_completed "MyString"
last_changed "2015-06-24 18:58:00"
compliance "MyString"
customer_id2 "MyString"
pricing_category "MyString"
pricing_category_description "MyString"
campaign_code "MyString"
campaign_code_description "MyString"
customer_status "MyString"
customer_status_description "MyString"
customer_info1 "MyString"
customer_info2 "MyString"
customer_info3 "MyString"
customer_info4 "MyString"
customer_info5 "MyString"
building_type "MyString"
building_type_description "MyString"
deliminated_address "MyString"
coding_quality "MyString"
location_id "MyString"
location_info1 "MyString"
location_info2 "MyString"
location_info3 "MyString"
location_info4 "MyString"
location_info5 "MyString"
monthly_charge "MyString"
job_points "MyString"
total_bablace_due "MyString"
ordering_operator_id "MyString"
contact_name "MyString"
contact_phone1 "MyString"
contact_phone2 "MyString"
drop_location "MyString"
tag_id "MyString"
house_status "MyString"
quota_group "MyString"
quota_area "MyString"
detail_text1 "MyString"
detail_text2 "MyString"
detail_text3 "MyString"
detail_text4 "MyString"
detail_text5 "MyString"
sms_job_number "MyString"
assigning_operator_id "MyString"
repeat "MyString"
repeat_count "MyString"
node_id "MyString"
tech_business_unit "MyString"
work_order nil
  end

end
