require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DriversLicesnsesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DriversLicesnse. As you add validations to DriversLicesnse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DriversLicesnsesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all drivers_licesnses as @drivers_licesnses" do
      drivers_licesnse = DriversLicesnse.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:drivers_licesnses)).to eq([drivers_licesnse])
    end
  end

  describe "GET #show" do
    it "assigns the requested drivers_licesnse as @drivers_licesnse" do
      drivers_licesnse = DriversLicesnse.create! valid_attributes
      get :show, {:id => drivers_licesnse.to_param}, valid_session
      expect(assigns(:drivers_licesnse)).to eq(drivers_licesnse)
    end
  end

  describe "GET #new" do
    it "assigns a new drivers_licesnse as @drivers_licesnse" do
      get :new, {}, valid_session
      expect(assigns(:drivers_licesnse)).to be_a_new(DriversLicesnse)
    end
  end

  describe "GET #edit" do
    it "assigns the requested drivers_licesnse as @drivers_licesnse" do
      drivers_licesnse = DriversLicesnse.create! valid_attributes
      get :edit, {:id => drivers_licesnse.to_param}, valid_session
      expect(assigns(:drivers_licesnse)).to eq(drivers_licesnse)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DriversLicesnse" do
        expect {
          post :create, {:drivers_licesnse => valid_attributes}, valid_session
        }.to change(DriversLicesnse, :count).by(1)
      end

      it "assigns a newly created drivers_licesnse as @drivers_licesnse" do
        post :create, {:drivers_licesnse => valid_attributes}, valid_session
        expect(assigns(:drivers_licesnse)).to be_a(DriversLicesnse)
        expect(assigns(:drivers_licesnse)).to be_persisted
      end

      it "redirects to the created drivers_licesnse" do
        post :create, {:drivers_licesnse => valid_attributes}, valid_session
        expect(response).to redirect_to(DriversLicesnse.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved drivers_licesnse as @drivers_licesnse" do
        post :create, {:drivers_licesnse => invalid_attributes}, valid_session
        expect(assigns(:drivers_licesnse)).to be_a_new(DriversLicesnse)
      end

      it "re-renders the 'new' template" do
        post :create, {:drivers_licesnse => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested drivers_licesnse" do
        drivers_licesnse = DriversLicesnse.create! valid_attributes
        put :update, {:id => drivers_licesnse.to_param, :drivers_licesnse => new_attributes}, valid_session
        drivers_licesnse.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested drivers_licesnse as @drivers_licesnse" do
        drivers_licesnse = DriversLicesnse.create! valid_attributes
        put :update, {:id => drivers_licesnse.to_param, :drivers_licesnse => valid_attributes}, valid_session
        expect(assigns(:drivers_licesnse)).to eq(drivers_licesnse)
      end

      it "redirects to the drivers_licesnse" do
        drivers_licesnse = DriversLicesnse.create! valid_attributes
        put :update, {:id => drivers_licesnse.to_param, :drivers_licesnse => valid_attributes}, valid_session
        expect(response).to redirect_to(drivers_licesnse)
      end
    end

    context "with invalid params" do
      it "assigns the drivers_licesnse as @drivers_licesnse" do
        drivers_licesnse = DriversLicesnse.create! valid_attributes
        put :update, {:id => drivers_licesnse.to_param, :drivers_licesnse => invalid_attributes}, valid_session
        expect(assigns(:drivers_licesnse)).to eq(drivers_licesnse)
      end

      it "re-renders the 'edit' template" do
        drivers_licesnse = DriversLicesnse.create! valid_attributes
        put :update, {:id => drivers_licesnse.to_param, :drivers_licesnse => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested drivers_licesnse" do
      drivers_licesnse = DriversLicesnse.create! valid_attributes
      expect {
        delete :destroy, {:id => drivers_licesnse.to_param}, valid_session
      }.to change(DriversLicesnse, :count).by(-1)
    end

    it "redirects to the drivers_licesnses list" do
      drivers_licesnse = DriversLicesnse.create! valid_attributes
      delete :destroy, {:id => drivers_licesnse.to_param}, valid_session
      expect(response).to redirect_to(drivers_licesnses_url)
    end
  end

end
